# Generated by Django 4.2.5 on 2023-09-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
            preserve_default=False,
        ),
    ]
