# Generated by Django 4.2.5 on 2023-09-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_sale_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='Oak', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='XL', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subheading',
            field=models.CharField(default='banitsi', max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
